In [1]:
import pandas as pd

In [2]:
row_data1 = pd.read_csv('row_data1.csv', encoding='cp949')
row_data2 = pd.read_csv('row_data2.csv', encoding='cp949')

In [3]:
row_data1.head()

,식품코드,식품명,데이터구분코드,데이터구분명,식품기원코드,식품기원명,식품대분류코드,식품대분류명,대표식품코드,대표식품명,...,출처코드,출처명,식품중량,업체명,데이터생성방법코드,데이터생성방법명,데이터생성일자,데이터기준일자,제공기관코드,제공기관명
0,D202-120000000-2408,피자_마라 피자 마라링 (R),D,음식,2,외식(프랜차이즈 등 업체 제공 영양정,2,빵 및 과자류,2120,피자,...,3,식품의약품안전처,539g,7번가피자,2,수집,2023-10-31,2024-04-16,1471000,식품의약품안전처
1,D202-120000000-2409,피자_마라 피자 석쇠 (L),D,음식,2,외식(프랜차이즈 등 업체 제공 영양정,2,빵 및 과자류,2120,피자,...,3,식품의약품안전처,694g,7번가피자,2,수집,2023-10-31,2024-04-16,1471000,식품의약품안전처
2,D202-120000000-2410,피자_마라 피자 석쇠 (R),D,음식,2,외식(프랜차이즈 등 업체 제공 영양정,2,빵 및 과자류,2120,피자,...,3,식품의약품안전처,439g,7번가피자,2,수집,2023-10-31,2024-04-16,1471000,식품의약품안전처
3,D202-120000000-2411,피자_마라 피자 씬바샤삭 (L),D,음식,2,외식(프랜차이즈 등 업체 제공 영양정,2,빵 및 과자류,2120,피자,...,3,식품의약품안전처,552g,7번가피자,2,수집,2023-10-31,2024-04-16,1471000,식품의약품안전처
4,D202-120000000-2412,피자_마라 피자 씬바샤삭 (R),D,음식,2,외식(프랜차이즈 등 업체 제공 영양정,2,빵 및 과자류,2120,피자,...,3,식품의약품안전처,404g,7번가피자,2,수집,2023-10-31,2024-04-16,1471000,식품의약품안전처

In [4]:
row_data1.columns

Index(['식품코드', '식품명', '데이터구분코드', '데이터구분명', '식품기원코드', '식품기원명', '식품대분류코드',
       '식품대분류명', '대표식품코드', '대표식품명', '식품중분류코드', '식품중분류명', '식품소분류코드', '식품소분류명',
       '식품세분류코드', '식품세분류명', '영양성분함량기준량', '에너지(kcal)', '수분(g)', '단백질(g)',
       '지방(g)', '회분(g)', '탄수화물(g)', '당류(g)', '식이섬유(g)', '칼슘(mg)', '철(mg)',
       '인(mg)', '칼륨(mg)', '나트륨(mg)', '비타민 A(μg RAE)', '레티놀(μg)', '베타카로틴(μg)',
       '티아민(mg)', '리보플라빈(mg)', '니아신(mg)', '비타민 C(mg)', '비타민 D(μg)',
       '콜레스테롤(mg)', '포화지방산(g)', '트랜스지방산(g)', '출처코드', '출처명', '식품중량', '업체명',
       '데이터생성방법코드', '데이터생성방법명', '데이터생성일자', '데이터기준일자', '제공기관코드', '제공기관명'],
      dtype='object')

In [5]:
row_data2.head()

,식품코드,식품명,데이터구분코드,데이터구분명,에너지(kcal),영양성분함량기준량,수분(g),단백질(g),지방(g),회분(g),...,수입여부,원산지국코드,원산지국명,업체명,데이터생성방법코드,데이터생성방법명,데이터생성일자,데이터기준일자,제공기관코드,제공기관명
0,P123-212020300-0410,반찬_유어스장충동불족발,P,가공식품,172,100g,NaN,12.78,6.67,NaN,...,N,NaN,해당없음,"(주)오뚜기,해당없음,해당없음",2,수집,2021-06-30,2024-04-16,1471000,식품의약품안전처
1,P123-212020300-0411,반찬_의정부식부대볶음,P,가공식품,168,100g,NaN,6.76,7.84,NaN,...,N,NaN,해당없음,"(주)하이푸드텍,해당없음,해당없음",2,수집,2021-06-30,2024-04-16,1471000,식품의약품안전처
2,P123-212020300-0412,반찬_이모네해물파전/셀프,P,가공식품,108,100g,NaN,8.49,1.32,NaN,...,N,NaN,해당없음,"(주)동원홈푸드,해당없음,해당없음",2,수집,2021-06-30,2024-04-16,1471000,식품의약품안전처
3,P123-212020300-0413,반찬_이베리코목살스테이크,P,가공식품,180,100g,NaN,8.69,14.36,NaN,...,N,NaN,해당없음,"주식회사아임셰프,해당없음,해당없음",2,수집,2021-06-30,2024-04-16,1471000,식품의약품안전처
4,P123-212020300-0414,반찬_이베리코목살스테이크1인,P,가공식품,207,100g,NaN,7.67,18.40,NaN,...,N,NaN,해당없음,"주식회사아임셰프,해당없음,해당없음",2,수집,2021-06-30,2024-04-16,1471000,식품의약품안전처

In [6]:
food_data1 = pd.DataFrame({'이름' : row_data1['식품명'],
                           '탄' : row_data1['탄수화물(g)'],
                           '단' : row_data1['단백질(g)'],
                           '지' : row_data1['지방(g)']})
food_data2 =  pd.DataFrame({'이름' : row_data2['식품명'],
                           '탄' : row_data2['탄수화물(g)'],
                           '단' : row_data2['단백질(g)'],
                           '지' : row_data2['지방(g)']})

In [7]:
food_data1.head()

                  이름   탄      단   지
0   피자_마라 피자 마라링 (R) NaN  17.04 NaN
1    피자_마라 피자 석쇠 (L) NaN  16.09 NaN
2    피자_마라 피자 석쇠 (R) NaN  16.36 NaN
3  피자_마라 피자 씬바샤삭 (L) NaN  11.59 NaN
4  피자_마라 피자 씬바샤삭 (R) NaN  12.87 NaN

In [8]:
food_data2.head()

                이름      탄      단      지
0     반찬_유어스장충동불족발  15.56  12.78   6.67
1      반찬_의정부식부대볶음  17.57   6.76   7.84
2    반찬_이모네해물파전/셀프  15.66   8.49   1.32
3    반찬_이베리코목살스테이크   4.43   8.69  14.36
4  반찬_이베리코목살스테이크1인   3.07   7.67  18.40

In [9]:
food_data = pd.concat([food_data1, food_data2])

In [10]:
food_data

                      이름      탄      단      지
0       피자_마라 피자 마라링 (R)    NaN  17.04    NaN
1        피자_마라 피자 석쇠 (L)    NaN  16.09    NaN
2        피자_마라 피자 석쇠 (R)    NaN  16.36    NaN
3      피자_마라 피자 씬바샤삭 (L)    NaN  11.59    NaN
4      피자_마라 피자 씬바샤삭 (R)    NaN  12.87    NaN
...                  ...    ...    ...    ...
49995     파이/만쥬_호두파이(냉동)  44.09   9.65  28.50
49996       파이/만쥬_호박맛쌀만쥬  56.67   6.67  18.33
49997    파이/만쥬_호호 레트로 만쥬  44.87   6.12  15.50
49998    파이/만쥬_후앙 파이시트생지  48.00   6.00  26.00
49999     프레즐_간식엔미니초코프레첼  58.00   8.00  12.00

[62151 rows x 4 columns]

In [11]:
food_data = food_data.reset_index()

In [12]:
food_data.rename(columns={food_data.columns[0] : '음식ID'},
                          inplace = True)

In [13]:
food_data

        음식ID                 이름      탄      단      지
0          0   피자_마라 피자 마라링 (R)    NaN  17.04    NaN
1          1    피자_마라 피자 석쇠 (L)    NaN  16.09    NaN
2          2    피자_마라 피자 석쇠 (R)    NaN  16.36    NaN
3          3  피자_마라 피자 씬바샤삭 (L)    NaN  11.59    NaN
4          4  피자_마라 피자 씬바샤삭 (R)    NaN  12.87    NaN
...      ...                ...    ...    ...    ...
62146  49995     파이/만쥬_호두파이(냉동)  44.09   9.65  28.50
62147  49996       파이/만쥬_호박맛쌀만쥬  56.67   6.67  18.33
62148  49997    파이/만쥬_호호 레트로 만쥬  44.87   6.12  15.50
62149  49998    파이/만쥬_후앙 파이시트생지  48.00   6.00  26.00
62150  49999     프레즐_간식엔미니초코프레첼  58.00   8.00  12.00

[62151 rows x 5 columns]

In [14]:
food_data[food_data.columns[0]] = range(1, len(food_data) + 1)

In [15]:
food_data

        음식ID                 이름      탄      단      지
0          1   피자_마라 피자 마라링 (R)    NaN  17.04    NaN
1          2    피자_마라 피자 석쇠 (L)    NaN  16.09    NaN
2          3    피자_마라 피자 석쇠 (R)    NaN  16.36    NaN
3          4  피자_마라 피자 씬바샤삭 (L)    NaN  11.59    NaN
4          5  피자_마라 피자 씬바샤삭 (R)    NaN  12.87    NaN
...      ...                ...    ...    ...    ...
62146  62147     파이/만쥬_호두파이(냉동)  44.09   9.65  28.50
62147  62148       파이/만쥬_호박맛쌀만쥬  56.67   6.67  18.33
62148  62149    파이/만쥬_호호 레트로 만쥬  44.87   6.12  15.50
62149  62150    파이/만쥬_후앙 파이시트생지  48.00   6.00  26.00
62150  62151     프레즐_간식엔미니초코프레첼  58.00   8.00  12.00

[62151 rows x 5 columns]

In [17]:
food_data.to_csv('food_data1.csv', index=False, encoding='cp949')